// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as ApiTrpcTrpcRoute from "@/app/api/trpc/[trpc]/route.info";
import * as PokemonRoute from "@/app/pokemon/page.info";
import * as PokemonIdRoute from "@/app/pokemon/[id]/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const ApiTrpcTrpc = makeRoute(
  "/api/trpc/[trpc]",
  {
    ...defaultInfo,
    ...ApiTrpcTrpcRoute.Route
  }
);
export const Pokemon = makeRoute(
  "/pokemon",
  {
    ...defaultInfo,
    ...PokemonRoute.Route
  }
);
export const PokemonId = makeRoute(
  "/pokemon/[id]",
  {
    ...defaultInfo,
    ...PokemonIdRoute.Route
  }
);

