// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "~/routes/routeInfo";
import * as PokemonPokemonIdRoute from "~/routes/pokemon/[pokemonId]/routeInfo";
import * as SearchRoute from "~/routes/search/routeInfo";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const PokemonPokemonId = makeRoute(
  "/pokemon/[pokemonId]",
  {
    ...defaultInfo,
    ...PokemonPokemonIdRoute.Route
  }
);
export const Search = makeRoute(
  "/search",
  {
    ...defaultInfo,
    ...SearchRoute.Route
  }
);

